export const SET_TOKEN = 'AUTH/SET_TOKEN'

export const GET_GROUPS = 'GROUP/GET_GROUPS'
export const FETCH_GROUPS = 'GROUP/FETCH_GROUPS'
export const REQUEST_GROUPS = 'GROUP/REQUEST_GROUPS'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'


